import { StyleSheet } from 'react-native';
import { heightPercentageToDP as hp, widthPercentageToDP as wp} from 'react-native-responsive-screen';

import { Metrics, ApplicationStyles, Colors } from '../../../shared/themes';

export default StyleSheet.create({
  container: {
    flex:1,
    height:hp('100'),
    backgroundColor: Colors.background,
  },
  header:{
    paddingHorizontal:wp('2'),
    paddingTop:hp('6'),
    height:hp('10'),
    flexDirection:'row',
    backgroundColor:Colors.white
  },
  haederTitle:{
    fontSize:wp('4'),
    color:Colors.primary,
    width:wp('50'),
    textAlign:'center'
  },
  content:{
    flex:1,
  },
  backbutton:{
    width:wp('20'),
      height:wp('18'),

  },
  listContent:{
    justifyContent:'center',
  },
  bookingbutton:{
    width:wp('95%'),
    alignSelf:'center',
    backgroundColor:Colors.primary,
    justifyContent:'center'
  },
  bookingbuttonText:{
    color:Colors.white,
    marginLeft:wp('2')
  },
  card:{
    width:wp('100'),
    flexDirection:'row',
    backgroundColor:Colors.white
  },
  left:{
    width:wp('23'),
    flexDirection:'column',
    alignItems:'center',
    padding:wp('5'),
    justifyContent:'flex-start',
  },
  username:{
    fontSize:wp('3'),
    color:Colors.title
  },
  image:{
    width:wp('15'),
    height:wp('15'),
    resizeMode:'contain'
},
section:{
  justifyContent:'flex-start',
  alignItems:'flex-start',
  paddingVertical:wp('2'),
  paddingHorizontal:wp('3'),

},
title:{
  fontSize:wp('3.5'),
  fontWeight:'bold',
  marginTop:hp('1.5'),
  color:Colors.text,
  textAlign:'center',

},
text:{
  marginTop:hp('0.5'),
  fontSize:wp('3'),
  color:Colors.text
},
  day:{
    fontSize:wp('6'),
    fontWeight:'bold',
    color:Colors.white
  },
  date:{
    fontSize:wp('4'),
    fontWeight:'400',
    color:Colors.white
  },
  center:{
    width:wp('55'),
    flexDirection:'column',
    justifyContent:'center',
    alignItems:'flex-start',
    paddingHorizontal:wp('2'),
  },
  
 

  
  detail:{
    marginTop:hp('1'),
    padding:wp('2'),
    width:wp('100'),
    flexDirection:'row',
    height:hp('5'),
    backgroundColor:Colors.background
  },
  detailLeft:{
      width:wp('20'),
      height:hp('4'),
      borderRadius:wp('1'),
      justifyContent:'center',
      alignItems:'center',
      backgroundColor:Colors.primary

  },
  detailLeftTitle:{
      color:Colors.white,
      fontWeight:'300',
      fontSize:wp('4')
  },
  detailRight:{
    width:wp('20'),
    height:hp('4'),
    borderRadius:wp('1'),
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:Colors.secondary

},
detailRightTitle:{
    color:Colors.white,
    fontWeight:'300',
    fontSize:wp('3.5')
},
  menu:{
      padding:wp('2'),
      width:wp('100'),
      flexDirection:'row',
      height:hp('10'),
      backgroundColor:Colors.background
  },
  
  leftTitle:{
      fontSize:wp('3.5'),
      fontWeight:'300',
      textAlign:'left',
      color:Colors.title,
      marginLeft:wp('2'),
      marginTop:wp('2')
  },
  leftText:{
    borderWidth:1,
    borderColor:Colors.text,
    padding:wp('1'),
    marginTop:hp('1'),
    fontSize:wp('5'),
    fontWeight:'600',
    textAlign:'left',
    color:Colors.text,
  },
  right:{
    width:wp('40'),
    flexDirection:'column',
    alignItems:'flex-start',
    justifyContent:'center'
  },
  city:{
    fontSize:wp('3.2'),
    fontWeight:'300',
    textAlign:'left',
    color:Colors.title,
    marginVertical:wp('2'),
  },
  rightTitle:{
    fontSize:wp('3.5'),
    fontWeight:'300',
    textAlign:'left',
    color:Colors.title,
  },
  rightText:{
    marginTop:hp('1'),
    fontSize:wp('3'),
    fontWeight:'600',
    textAlign:'left',
    color:Colors.primary,
  },
  centerborder:{
    marginTop:hp('3'),
    backgroundColor:Colors.primary,
    width:wp('50'),
    height:hp('0.2'),
    alignItems:'center',
    justifyContent:'center'
  },
  row:{
    backgroundColor:Colors.white,
    height:hp('10'),
    flexDirection:'row',
    justifyContent:'space-around',
    alignItems:'center'

  },
  col:{
    borderRightWidth:1,
    borderRightColor:Colors.background,
    width:wp('31'),
    height:hp('7'),
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:Colors.white
  },
  colTitle:{
    color:Colors.title,
    fontSize:wp('4'),
    fontWeight:'bold'
  },
  colText:{
    color:Colors.text,
    fontSize:wp('3'),
    fontWeight:'400'
  },
  textStyle:{
    color:Colors.white,
  },
  activeTextStyle:{
    color:Colors.white,
  },
  seatView:{
      flex:1,
      marginVertical:hp('4')
  },
  seatcontent:{
      flex:1,
      justifyContent:'flex-start',
      alignItems:'center'
  },
  seat:{
      width:wp('17'),
      height:wp('17'),
      borderRadius:wp('1'),
      justifyContent:'center',
      alignItems:'center',
      marginHorizontal:wp('5'),
      marginVertical:wp('6'),
      backgroundColor:Colors.third
  },
  seatTitle:{
      fontSize:wp('4'),
      color:Colors.white,
      fontWeight:'400'

  },
  selectedSeat:{
    width:wp('17'),
    height:wp('17'),
    borderRadius:wp('1'),
    justifyContent:'center',
    alignItems:'center',
    marginHorizontal:wp('5'),
    marginVertical:wp('6'),
    backgroundColor:Colors.primary
},
 rating:{ 
   marginVertical: hp('1'),
  },
  buttonCard:{
    width:wp('5'),
    height:hp('2.5'),
    marginHorizontal:wp('1'),
    backgroundColor:Colors.primary,
    borderRadius:wp('0.5')

  },
  buttonTitle:{
    padding:wp('1'),
    borderRadius:hp('10'),
    justifyContent:'center',
    alignItems:'center',
    color:Colors.text,
    fontSize:hp('1.5'),
    fontWeight:'500'
  },
  badge:{
    paddingVertical:wp('1'),
    paddingHorizontal:wp('2'),
    borderRadius:hp('0.3'),
    justifyContent:'center',
    alignItems:'center',
    color:Colors.white,
    backgroundColor:Colors.primary
  },
  badgeText:{
    fontSize:wp('3'),
    color:Colors.white,
  },
  
  icon:{
      width:wp('8'),
      height:wp('8'),
      tintColor:Colors.primary
  },
  price:{
    color:Colors.primary,
    fontWeight:'bold',
    fontSize:wp('5')
  },
  footer:{
      flexDirection:'column',
      height:hp('15'),
  },
  footerTitle:{
      color:Colors.title,
      fontWeight:'400',
      fontSize:wp('3'),
      marginLeft:wp('4'),
  },
  footerText:{
    color:Colors.text,
    fontWeight:'700',
    fontSize:wp('3'),
    marginRight:wp('4'),
    textAlign:'right',
  },
  button:{
    alignSelf:'center',
    alignItems:'center',
    flexDirection:'row',
    justifyContent:'center',
    paddingTop:1,
    width: wp('95%'),
    height:hp('5%'),
    backgroundColor:Colors.primary,
    color: Colors.primary,
    borderRadius:wp('1')
   },
   buttonText: {
    color: Colors.white,
    fontSize: 16,
  },
  steering:{
      tintColor:Colors.white,
      width:wp('15'),
      height:wp('15')
  },
  model:{
    justifyContent: 'flex-end',
    margin: 0,
  },
  modelView:{
    height:hp('60'),
    width:wp('100'),
    padding:wp('2'),
    backgroundColor:Colors.white
  },
  modelHeader:{
    flexDirection:'row',
    justifyContent:'space-between',
    
  },
  modelTitle:{
    fontSize:wp('4'),
    marginTop:hp('1'),
    color:Colors.primary
    
  },
  modelContent:{
    flex:1,
  },
});
