// leave off @2x/@3x
const images = {
  bus: require('../images/bus.png'),
  cardLogo:require('../images/beso-card.png'),
  box: require('../images/package.png'),
  taxi: require('../images/taxi.png'),
  steering: require('../images/steering.png'),
  arrowRight: require('../images/right-arrow.png'),
  logo: require('../images/logo-v3.png'),
  logoJhipster: require('../images/logo-jhipster.png'),
  toggleDrawerIcon: require('../images/toggle-drawer-icon/toggle-drawer-icon.png'),
  setting:require('../images/settings.png'),
  logout:require('../images/logout.png'),
  support:require('../images/support.png'),
  home:require('../images/home.png'),
  booking:require('../images/ticket.png'),
  profile:require('../images/user.png'),
  car:require('../images/car.png'),
  call:require('../images/phone-call.png'),
  email:require('../images/arroba.png'),
  chat:require('../images/chat.png'),
  seat:require('../images/seat.png'),
  seatSelected:require('../images/seat-selected.png'),
  seatBooked:require('../images/seat-booked.png'),
  Edahab:require('../images/edahab.png'),
  Zaad:require('../images/zaad.png'),
  dropdown:require('../images/dropdown.png'),
  money:require('../images/money.png'),
  exchange:require('../images/exchange.png'),
  send:require('../images/send.png'),
  card:require('../images/credit-card.png'),
  check:require('../images/check.png'),
  lock:require('../images/lock.png'),
  upload:require('../images/upload.png'),
  premeir:require('../images/premeir.png'),
  edahabLogo:require('../images/edahab-logo.png'),
  privacy:require('../images/privacy.png'),
  term:require('../images/contract.png'),
  Borrow:require('../images/borrow.png'),
  Lend:require('../images/lend.png'),
  Receive:require('../images/borrow-send.png'),
  Send:require('../images/lend-receive.png'),
  trash:require('../images/delete.png'),
  product:require('../images/product.png'),
  star:require('../images/star.png'),
  camera:require('../images/camera.png'),
  visa:require('../images/visacard.png'),
  mastedcard:require('../images/mastercard.png'),
  golis:require('../images/golis.png'),
  evc:require('../images/evc.png'),
  brokenimg:require('../images/broken-image.png'),
  menu:require('../images/menu.png'),
  header:require('../images/header.png'),
  grid:require('../images/grid.png'),
  book:require('../images/bookmark.png'),
  wallpaper:require('../images/wallpaper.png'),
  wallpaper2:require('../images/wallpaper-2.png'),
  wallpaper5:require('../images/wallpaper-5.png'),
  wallpaper4:require('../images/wallpaper-4.png'),
  left:require('../images/left.png'),
  deleteUser:require('../images/delete-user.png'),
  onebox:require('../images/onebox.png'),
  language:require('../images/language.png'),
  share:require('../images/share.png'),
  google:require('../images/google.png'),
  facebook:require('../images/facebook.png'),
  intro:require('../images/intro.jpg'),

};

export default images;
